# .github/workflows/cd.yml

name: CD - Test to Main

on:
  pull_request:
    branches:
      - main # Triggered by any PR that targets the 'main' branch
    types: [opened, synchronize, reopened]
    
jobs:
  final_deployment:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      # --- CRITICAL BRANCH ENFORCEMENT SCRIPT ---
      # This fails the workflow if the source branch is not exactly 'test'
      - name: CHECK PR SOURCE BRANCH
        run: |
          HEAD_REF="${{ github.event.pull_request.head.ref }}"
          echo "Source Branch: $HEAD_REF"
          if [ "$HEAD_REF" != "test" ]; then
            echo "::error::INVALID SOURCE: Merge into 'main' is only allowed from the 'test' branch. Workflow FAILED."
            exit 1 # Fails the workflow status check
          fi
          echo "Source branch is 'test'. Proceeding with deployment steps."

      # --- Deployment Steps ---
      
      # Optional: Download the artifact that passed the CI stage
      # - name: Download Tested Artifact
      #   uses: actions/download-artifact@v4
      #   with:
      #     # We use a known artifact name, or you can rebuild if faster
      #     name: document-build-${{ github.event.pull_request.head.sha }}
      #     path: ./site 

      - name: Deploy Documents to Production
        # This step requires secrets for access (e.g., AWS_SECRET_ACCESS_KEY, DEPLOY_TOKEN)
        run: |
          echo "Starting production deployment..."
          # *** REPLACE with your actual deployment command (e.g., rsync, gh pages deploy) ***
          
      - name: Smoke Test (Verify basic deployment success)
        run: echo "Verify the live site is accessible (e.g., run curl -I https://yoursite.com)"
